### PR TITLE
ID-3661 [Fix] Accounts linked to SSO don't need to set up 2FA or change passwords

### PR DESCRIPTION
**Pull request by tonytlwu**
Ref. https://weboo.atlassian.net/browse/ID-3661

### CODE REVIEW

**Review by simonchapman1986 — APPROVED** [review]

**Comment by simonchapman1986** [comment]
pipeline issues @tonytlwu ... went to have a look, but perm issues? odd

**Comment by tonytlwu** [comment]
@simonchapman1986 I'm actually not sure why there's a CI pipeline for this repo at all. There's no need for one and don't know where it's set up. I'll ignore this and continue for now.

**Comment by tonytlwu** [comment]
@inna-bieshulia This is ready for testing

Skip compile: 
Includes translation: 
Initiative: 
Impact: High
Affected: All Fliplet Viewer users
Verify: Fliplet Viewer users can log in and stay logged in with different login methods

**Comment by simonchapman1986** [comment]
> @simonchapman1986 I'm actually not sure why there's a CI pipeline for this repo at all. There's no need for one and don't know where it's set up. I'll ignore this and continue for now.

that would explain why it failed 😆 
i have told circleci to stop caring about the project.. looks like it auto-picked it up, and failed when it didn't have a config for it.
https://app.circleci.com/settings/project/github/Fliplet/fliplet-widget-fliplet-login?return-to=https%3A%2F%2Fapp.circleci.com%2Fprojects%2Fproject-dashboard%2Fgithub%2FFliplet%2F

**Comment by simonchapman1986** [comment]
Risk: medium
Affected: Authentication
Verify:
- new accounts linked to SSO not prompted to setup 2FA
- existing accounts linked to SSO not prompted to setup 2FA
- accounts not linked to SSO are still prompted to setup 2FA (regression)
- create new account and functions as expected still (regression)
- already existing accounts don't run into issues - can still login etc (regression)

**Pull request merged**
